### ISSUE TITLE
java.lang.NoClassDefFoundError: com.facebook.android.R$layout

### ISSUE THREAD

**Issue by somentelucas** [ccsoft/cordova-facebook#14]
Hi,

I'm trying to install the plugin only using command line. I added the plugin and then I referenced the FB SDK adding this line to my `project.properties`

```
android.library.reference.2=../../../../../../Library/facebook-android-sdk-3.6.0/facebook
```

(I have tried versions 3.6.0 and also 3.14.0)

Everything is compiling and when my application is running and I try to login I get the following error:

```
E/AndroidRuntime( 1141): FATAL EXCEPTION: main
E/AndroidRuntime( 1141): java.lang.NoClassDefFoundError: com.facebook.android.R$layout
E/AndroidRuntime( 1141):    at com.facebook.LoginActivity.onCreate(LoginActivity.java:57)
E/AndroidRuntime( 1141):    at android.app.Activity.performCreate(Activity.java:5206)
E/AndroidRuntime( 1141):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
E/AndroidRuntime( 1141):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
E/AndroidRuntime( 1141):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
E/AndroidRuntime( 1141):    at android.app.ActivityThread.access$700(ActivityThread.java:140)
E/AndroidRuntime( 1141):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
E/AndroidRuntime( 1141):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1141):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1141):    at android.app.ActivityThread.main(ActivityThread.java:4921)
E/AndroidRuntime( 1141):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1141):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1141):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
E/AndroidRuntime( 1141):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
E/AndroidRuntime( 1141):    at dalvik.system.NativeStart.main(Native Method)
```

Might I be referencing FB SDK wrong only by adding that line?

Thanks

**Comment by leonprou** [comment]
As I see the problem is that the command line tool doesn't create the gen folder with com/facebook/android/R.java file, that's why it missing.  When I do the process in eclipse the folder with files is there.  Instead of it, the cordova tool just puts the content of facebook's R.java to ant-gen/co/<your projects>/R.java.

**Comment by somentelucas** [comment]
@leonprou Did you find any way of generating it?

**Comment by lucas-garcia** [comment]
@leonprou, I solved it by going to the facebook folder and runing `ant release`

**Comment by somentelucas** [comment]
@leonprou I solved it by going to the facebook folder and running `ant release`

**Comment by leonprou** [comment]
@somentelucas 
Thanks, I don't remember how but I solved that issue, and it doesn't appear again.

It was something wrong in my ant configs I guess (mixing up cordova-cli and eclipse IDE is a bad practise also)
