### ISSUE TITLE
Login failed or closed

### ISSUE THREAD

**Issue by NeXTs** [ccsoft/cordova-facebook#21]
Does someone else getting "login call failed with error: Login failed or closed" on login?

I've tried iOS SDK 3.13.1 as you mentioned you tested that, tried the last one 1.16.1. And all time getting this message after login. I have tried login with various permissions such as "basic_info" and "public_profile" on init, even with this changes https://github.com/ccsoft/cordova-facebook/issues/18#issuecomment-48935202 but without success :(

Any ideas what could be wrong?

**Comment by JackNova** [comment]
I had similar problems, in my case the solution was to make sure of following things:
- correct configuration in the app .plist (I was using a different bundle id for a test version of the app and this should be configured accordingly, I had to create a test version of the app on facebook where I configured the appropriate bundle id).
- if you have a test version of the fb app it should be either publicly available or it should have some test users configured through the ROLES tab of the app.
- for further insights refer to this StackOverflow question: http://stackoverflow.com/questions/23509386/facebook-sdk-on-ios-app-session-fixing/28673422#28673422

**Comment by braco** [comment]
Note to future searchers, I got "login call failed with error: Login failed or closed" because the appdelegate.m code (as shown in README) got wiped out during a build.
