### ISSUE TITLE
invite method

### ISSUE THREAD

**Issue by ajinkyapote1** [ccsoft/cordova-facebook#60]
First of all thanks for the simple plugin.
I have the issue with the invite method, it open web dialog with the list of friends and allow me to invite requests. but my friends whom i have sent invitation don't see any invitation.
Please help me in this. I am using facebook SDK 3.18.

Thanks in advance.

**Comment by ajinkyapote1** [comment]
Hello Sir,
              Now i have made my app public but still don't see invitation requests.
Please help me.
One more question, before sending invitation i am making graph api call to get friend list which returns me only those users which have registered with the app via Facebook.

Thanks in advance.

**Comment by koraybalci** [comment]
Facebook recently changed the invite api, you cannot invite people who have not already users of your app. Please check the facebook developer documentation. 

About your invites not reaching, there might be several reasons, you might be getting errors (are you?) during invite sending. I can't really comment, you can debug though.

**Comment by ajinkyapote1** [comment]
After invite request i am getting request id and invited friends ids. But they don't see invitation requests on their facebook page.

**Comment by koraybalci** [comment]
That's all you can expect from the plugin. If you have request id, you can debug it in facebook debug console with graph api probably. I really don't think the problem is plugin related.
