### ISSUE TITLE
IOS weird login flow

### ISSUE THREAD

**Issue by mpmisha** [ccsoft/cordova-facebook#63]
Hello, 
trying to create a facebook login for my app,
on android it works fine , but on IOS i get some weird flow
the current code is like so:

<code>
plugin.init(appId, appNmae,['public_profile', 'email', 'publish_actions'], 

                function(response) {

                        plugin.login(function(response) {

                            plugin.info(function(userData) {

                   ------here comes my code for in app login using the userData and token----

                                },function(err) {alert(JSON.stringify(err));console.log(err);}

                            );

                        }), function(){};

                }), function(){};

</code>

The result i get is :
0) Launch the app (facebook app not authorized on the account yet)
1) click on the login btn (runs the script above)
2) facebook login page displayed ('myApp' will recieve the following info....) -->click Ok
3) Facebook app goes away, then a black screen for a few seconds, then facebook splashscreen appears and then the browser opens in facebook.com and shows a screen saying: "you have already authorized 'myApp'
4)I click Ok, and get back to the app (not logged in)
5)click on 'login with facebook' again (in my app)
6)login successfull within a second.

As i was sying, on android it works like a charm
Any ideas?

**Comment by koraybalci** [comment]
You should not be needing step 5, you probably did not update your app with the data you received from the login callback in your own js side. just guessing.

publish_actions requires extra confirmation from user, so you see a second facebook auth screen. I presume you already approved the app in another device (android?), so it just displays "you have already authorized.." message.

I think, this is the correct behavior, but I might be wrong since facebook keeps changing the flow and I cannot catch up with them lately.

**Comment by mpmisha** [comment]
I have dug deeeper, and it seems that after i authorize the app for the first time (step (2)) and launches the second auth page (step (3)) and afterwards the app crashes (that is the reason for the second launch) ,
the error i recieve is :  <code>
 *** Terminating app due to uncaught exception 'com.facebook.sdk:InvalidOperationException', reason: 'FBSession: It is not valid to reauthorize while a previous reauthorize call has not yet completed.'
</code>

I guess it happens because  of the publish permmision

**Comment by mpmisha** [comment]
update : when removing the "publish_actions" , all works well
but i need the publish actions..
can i ask for them synchronically?

**Comment by koraybalci** [comment]
I am not sure about the exact problem, but the sample app (linked as a separate repo in readme) asks for publish_actions and works well for ios. Perhaps, you can start with that. You can also check your FB SDK version, we are not supporting the latest one, please check the readme of repo.

**Comment by koraybalci** [comment]
Have you found a solution? Can I close this issue?

**Comment by mpmisha** [comment]
yes I did,
thank you
