### ISSUE TITLE
Android 5.0 / Lollipop

### ISSUE THREAD

**Issue by Hirbod** [ccsoft/cordova-facebook#64]
Hi,

Could anyone get this plugin work on lollipop? I don't have a 5.0 System here but people are reporting that they can't login with my app since 5.0 (they stuck on the loading spinner).

I do not have any clue what's going wrong there since I does not have 5.0.

Any help or maybe knowing issues will be appreciated!

**Comment by Hirbod** [comment]
Hi,

just some more informations: the "crash" only occurs, when facebook app is installed. Without, it seems to work on Android 5.0.

Going live should be today, I really appreciate any fast help.. This is actually the worst case that could happen so close to release :(

**Comment by koraybalci** [comment]
What version is your Facebook SDK?

**Comment by Hirbod** [comment]
3.18.1

**Comment by koraybalci** [comment]
I would try with 3.18, I remember people reporting breaking changes and issues with upper versions. I never had the chance to look at version > 3.18

**Comment by Hirbod** [comment]
But everything works < android 5.
3.18.1 is just a small bugfix release, it should not break anything

**Comment by Hirbod** [comment]
But 3.18.2 has something:

```
FacebookSDK.framework
Fixed

    Re-added armv7s architecture

FBAudienceNetwork.framework
Fixed

    Re-added armv7s architecture
```

Could some armv7s be missing for Nexus 5? I'm really not up to date with android as I do iOS most of the time..

**Comment by koraybalci** [comment]
Ok then. I wish I had an Android 5.0 device then :) Unfortunately, installing a new simulator and installing Facebook app on it is sth I cannot do right now. Hope someone else can.

Your comment on 3.18.2 is about iOS by the way.

**Comment by Hirbod** [comment]
Deleted last entry, as it was iOS related- sorry

**Comment by Hirbod** [comment]
Is there any way to install the Facebook app on an emulator? Maybe I could provide more informations then. I dont even had "Play Store" on the emulator..

**Comment by koraybalci** [comment]
Yes, it should be possible. I remember reading a lengthy procedure to install it sometime ago.

**Comment by Hirbod** [comment]
Managed to get the app installed (won't work with Intel HAXM, only ARM)
Official downloaded facebook.apk, moved APK inside of sdk-path -> platform-tools and run ```adb install appname.apk```

I hope I can debug now. Stay tuned.

**Comment by Hirbod** [comment]
The app is installed, but whatever I do, I can't login with facebook. Oh gosh..,

**Comment by koraybalci** [comment]
I just tried with Facebook SDK 3.23 on a real Android 5 device and had no problem logging in with FB app installed.

You don't need to do anything with the plugin, just upgrade your FacebookSDK to 3.23 and update your eclipse reference.

Let me know if it works.

**Comment by Hirbod** [comment]
Hi,

thanks for the response. So your plugin works out of the box with the newest SDK?

Same for iOS?

**Comment by koraybalci** [comment]
For Android, yes. Tested with 4.4 and 5 devices.

I suppose that's not the case for iOS. :(

**Comment by Hirbod** [comment]
Hi @koraybalci 

I've updated the SDK without problem, everything works well so far. I've pushed the app to the guys with 5.0, let's see what they will report (cause I couldn't reproduce any bugs on emulator)

Did you also encounter a login issue or do you think it was SDK related? If you can confirm that you had a login bug which was fixed with 3.23 I would be very happy :)

**Comment by koraybalci** [comment]
Unfortunately, I didn't test Lolipop with sdk < 3.23

**Comment by Hirbod** [comment]
Hi, 

just got answer of the guy with Nexus 5.. Same problem. Can't use the login with Android 5 on a real device. I got three reports now. This is so strange.

**Comment by koraybalci** [comment]
Sorry to hear that. Can you build and ask them to try sample application?
https://github.com/ccsoft/cordova-sample/tree/facebook

Then we can confirm it's plugin related.
