### ISSUE TITLE
init method does not responds in cordova android method

### ISSUE THREAD

**Issue by Mitesh-Baviskar** [ccsoft/cordova-facebook#66]
The init method does not work properly it executes properly for one application and does not respond for another application within same environment
Following warning / Error / info messages were found in LogCat

Could not find method com.facebook.Session.getAccessToken, referenced from method com.ccsoft.plugin.CordovaFacebook.prepareAccessTokenInfo

DexOpt: unable to optimize static field ref 0x0745 at 0x304 in Lcom/ccsoft/plugin/CordovaFacebook;.execute

I/dalvikvm(12811): DexOpt: unable to optimize static field ref 0x0743 at 0x310 in Lcom/ccsoft/plugin/CordovaFacebook;.execute
I/dalvikvm(12811): Failed resolving Lcom/ccsoft/plugin/CordovaFacebook$16; interface 973 'Lcom/facebook/Request$Callback;'

**Comment by koraybalci** [comment]
You are either using an unsupported version of Facebook SDK or not included Facebook SDK properly in your project. Most likely the latter.

The error seem to say the plugin cannot find a method from Facebook library.
