### ISSUE TITLE
AppID not found

### ISSUE THREAD

**Issue by braco** [ccsoft/cordova-facebook#76]
Upgraded Cordova to 5.x and Xcode, started getting this:

```
*** Terminating app due to uncaught exception 'com.facebook.sdk:InvalidOperationException', reason: 'FBAppBridge: AppID not found; Add a string valued key with the appropriate id named FacebookAppID to the bundle *.plist'
```

**Comment by koraybalci** [comment]
I don't think it's related to either plugin or the cordova/xcode upgrade. Do you have AppId defined properly (as the error message points out)?
