### ISSUE TITLE
autologin using facebook

### ISSUE THREAD

**Issue by znnsamp** [ccsoft/cordova-facebook#78]
Is there a way to allow the user to login with facebook without them every having to use a password? I've seen apps that allow the user to use the existing session information from their facebook app, and I'm wondering if this is available through cordova-facebook

Thanks

**Comment by koraybalci** [comment]
Yes, this is the purpose of this plugin.

**Comment by znnsamp** [comment]
I thought this might be the case. I still feel silly though :sweat_smile: : Thank you
